title: Good for People of Color in Tech
email: support@goodforpocin.tech
description: We gotta support our own.
long_description: A growing list of companies providing inclusive and safe work environments for people of color in tech.
baseurl: ""
url: http://www.goodforpocin.tech
twitter_username: goodforpocintech
github_username: goodforpocintech

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-assets

assets:
  compress:
    css: true
    js: true
  # cache: false
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  autowrite: true
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: true
    automatic_img_size: true
    automatic_img_alt : true

picture:
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      width: 825
      height: 600
