title: Good for People of Color in Tech
email: support@goodforpocin.tech
description: We gotta support our own.
baseurl: /
url: "http://goodforpocin.tech" # the base hostname & protocol for your site
twitter_username: goodforpocintech
github_username: goodforpocintech

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
